### ISSUE TITLE
Possible Typo in RIPEMD-320 C Implementation

### ISSUE THREAD

**Issue by MrM21632** [nayuki/Native-hashes-for-Java#4]
I noticed that in ripemd320-compress.c, `ripemd320_compress_block` takes a parameter `uint32_t state[8]`. However, in the method, `state` is assumed to have ten values:

```c
// After the ROUND definitions
uint32_t al = state[0], ar = state[5];
uint32_t bl = state[1], br = state[6];
uint32_t cl = state[2], cr = state[7];
uint32_t dl = state[3], dr = state[8];
uint32_t el = state[4], er = state[9];
```

The other RIPEMD implementations don't have this issue.

**Comment by nayuki** [comment]
You are right, I made a mistake. Thank you so much! Fixed right now in https://github.com/nayuki/Native-hashes-for-Java/commit/90ba469ab55ad78a5a269c4e68939863e53477bd .

I must have been copying and pasting function signatures while writing the code. In C, the leftmost dimension of an array parameter is for human reading but has no effect on the code, so all these are the same to the compiler:

    void foo(int *a);
    void foo(int a[]);
    void foo(int a[3]);

My code does behaves correctly at run time because the caller allocates a 10-element array:

https://github.com/nayuki/Native-hashes-for-Java/blob/e3a699326a7e8d1e5b61c71778b245159118174a/native/ripemd320-jni.c#L12

https://github.com/nayuki/Native-hashes-for-Java/blob/e3a699326a7e8d1e5b61c71778b245159118174a/native/ripemd320-jni.c#L32

https://github.com/nayuki/Native-hashes-for-Java/blob/e3a699326a7e8d1e5b61c71778b245159118174a/native/ripemd320-jni.c#L41
